version: '3.8'
services:
  redis:
    image: redis:6.2-alpine
  producer:
    build: .
    ports:
      - 8080:3000
    command: nest start producer
  consumer:
    build: .
    ports:
      - 8081:3000
    command: nest start consumer
